apiVersion: apps/v1
kind: Deployment
metadata:
  name: minimal-tiktok
spec:
  selector:
    matchLabels:
      app: tiktok
  replicas: 2
  template:
    metadata:
      labels:
        app: tiktok
    spec:
      containers:
      - name: tiktok
        image: codingdog1412/tiktok
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: tiktok
  labels:
    app: tiktok
spec:
  ports:
  - name: tiktok
    port: 8080
  selector:
    app: tiktok