FROM golang:1.18-alpine
MAINTAINER codingdog1412
WORKDIR /opt/tiktok

RUN go mod init github.com/bytedance2022/minimal_tiktok

COPY grpc_gen/biz grpc_gen/biz
COPY pkg pkg
COPY cmd/biz cmd/biz

RUN go env -w GOPROXY="https://goproxy.cn, direct" && go mod tidy
RUN go build -v -o /usr/local/bin/biz ./cmd/biz/*.go