FROM golang:1.18-alpine
MAINTAINER codingdog1412
WORKDIR /opt/tiktok

RUN go mod init github.com/bytedance2022/minimal_tiktok

COPY cmd/auth cmd/auth
COPY grpc_gen grpc_gen
COPY config config
COPY pkg pkg

# RUN go env -w GOPROXY="https://goproxy.cn, direct" && go mod download && go mod verify
RUN go env -w GOPROXY="https://goproxy.cn, direct" && go mod tidy
RUN go build -v -o /usr/local/bin/auth ./cmd/auth/*.go